<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AWSProjectType>Lambda</AWSProjectType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Amazon.Lambda.Core" Version="2.2.0" />
		<PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.0" />
		<PackageReference Include="Amazon.Lambda.SQSEvents" Version="2.2.0" />
		<PackageReference Include="AWSSDK.SQS" Version="3.7.300.0" />
	</ItemGroup>

</Project>